name: RT-AK with plugin-example CI

on: [push, pull_request]

jobs:
  RT-AK-Github-Actions:
    runs-on: ubuntu-18.04
    env:
      TEST_BSP_ROOT: ../AutoTestBsp

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.7

    - name: Install dependecies
      run: |
        sudo apt-get -yqq install scons qemu-system git
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install Arm ToolChains
      run: |
        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/arm-2017q2-v6/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 
        sudo tar xjf gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 -C /opt
        /opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc --version
        
        
    - name: Get Test_BSP
      run: |
        git clone https://github.com/armink/EasyFlashAutoTestBSP $TEST_BSP_ROOT

    - name: Build BSP
      run: |
        export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-6-2017-q2-update/bin
        echo CONFIG_RT_USING_UTESTCASES=y >> $TEST_BSP_ROOT/.config
        echo CONFIG_UTEST_SELF_PASS_TC=y >> $TEST_BSP_ROOT/.config
        scons --pyconfig-silent -C $TEST_BSP_ROOT
        scons -j$(nproc) -C $TEST_BSP_ROOT
        ls $TEST_BSP_ROOT

    - name: Get UtestRunner
      run: |
        git clone https://github.com/armink/UtestRunner.git
      
    - name: Start test
      run: |
        ls
        pushd UtestRunner
        ls
        python3 qemu_runner.py --elf $TEST_BSP_ROOT/rtthread.bin
        cat rtt_console.log
        popd
