name: RT-AK with plugin-example CI

on: [push, pull_request]

jobs:
  RT-AK-Github-Actions:
    runs-on: ubuntu-18.04

  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Python
    uses: actions/setup-python@v2.2.1
    with:
      python-version: 3.7
    
  - name: Install dependecies
    run: |
      sudo apt-get -yqq install scons qemu-system git
      python -m pip install --upgrade pip
      pip install flake8 pytest
  
  - name: Lint with flake8
    run: |
      # stop the build if there are Python syntax errors or undefined names
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  - name: Install Arm ToolChains
    run: |
      wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/arm-2017q2-v6/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 
      sudo tar xjf gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 -C /opt
      /opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc --version

  - name: Build BSP
    run: |
      export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-6-2017-q2-update/bin
      git clone https://github.com/armink/EasyFlashAutoTestBSP $TEST_BSP_ROOT
      scons -j$(nproc) -C $TEST_BSP_ROOT

  - name: Start test
    run: |
      python3 qemu_runner.py --elf $TEST_BSP_ROOT/rtthread.elf --sd $TEST_BSP_ROOT/sd.bin
      cat rtt_console.log
