name: RT-AK with plugin-stm32 CI

on: [push, pull_request]

jobs:
  RT-AK_Plugin-stm32_Actions:
    runs-on: ubuntu-18.04
    env:
      TEST_BSP_ROOT: ../AutoTestBsp

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.7
      
    - name: Install dependecies
      run: |
        sudo apt-get -yqq install unzip git
        python -m pip install --upgrade pip
        pip install flake8 pytest scons
    
    - name: Install Arm ToolChains
      run: |
        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/arm-2017q2-v6/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 
        sudo tar xjf gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 -C /opt
        /opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc --version

    - name: Install X-CUBE-AI
      run: |
        wget -q http://117.143.63.254:9012/www/RT-AK/stm32ai-linux-5.2.0.zip
        unzip -q stm32ai-linux-5.2.0.zip -d /opt/x-cube-ai
        /opt/x-cube-ai/linux/stm32ai --version

    - name: Prepare ART-Pi BSP
      run: |
        git clone https://github.com/EdgeAIWithRTT/ART-Pi_BSP $TEST_BSP_ROOT

    - name: Run RT-AK
      run: |
        git clone https://github.com/lebhoryi/RT-AK.git --depth 1
        pushd RT-AK/RT-AK/rt_ai_tools
        python aitools.py --project=../../../$TEST_BSP_ROOT --platform=stm32 --ext_tools=/opt/x-cube-ai/linux --clear
        popd
    
    - name: Build BSP
      run: |
        export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-6-2017-q2-update/bin
        scons -j$(nproc) -C $TEST_BSP_ROOT
        echo "Compile done."
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with: 
        name: rthread
        path: $TEST_BSP_ROOT
        if-no-files-fount: error

    # app test

    # test case (pytest)
